insert into Spitter (username, password, fullname, email, updateByEmail) values ('habuma', 'haslo', 'Craig Walls', 'craig@habuma.com', false);
insert into Spitter (username, password, fullname, email, updateByEmail) values ('mwalls', 'haslo', 'Michael Walls', 'mwalls@habuma.com', true);
insert into Spitter (username, password, fullname, email, updateByEmail) values ('chuck', 'haslo', 'Chuck Wagon', 'chuck@habuma.com', false);
insert into Spitter (username, password, fullname, email, updateByEmail) values ('artnames', 'haslo', 'Art Names', 'art@habuma.com', true);

insert into Spittle (spitter, message, postedTime) values (1, 'Testowa wiadomość spittle', '2012-06-09 22:00:00Z');
insert into Spittle (spitter, message, postedTime) values (1, 'Jeszcze jedna testowa wiadomość spittle', '2012-06-09 22:10:00Z');
insert into Spittle (spitter, message, postedTime) values (1, 'Trzecia testowa wiadomość spittle', '2012-07-04 23:30:00Z');
insert into Spittle (spitter, message, postedTime) values (2, 'Pozdrowienia od Chucka!', '2012-03-25 12:15:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Cześć od Arta!', '2012-03-25 12:15:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Ponowne cześć od Arta!', '2012-03-25 12:25:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Hola od Artura!', '2012-03-25 12:35:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Buenos Dias od Artura!', '2012-03-25 12:45:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Ni Hao od Artura!', '2012-03-25 12:55:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Guten Tag od Artura!', '2012-03-25 13:05:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Konnichi wa od Artura!', '2012-03-25 13:15:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Buon giorno od Artura!', '2012-03-25 13:25:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Bonjour od Artura!', '2012-03-25 13:35:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'Aloha od Artura!', '2012-03-25 13:45:00Z');
insert into Spittle (spitter, message, postedTime) values (4, 'God dag od Artura!', '2012-03-25 13:55:00Z');
